### ISSUE TITLE
CR0010 - Enhance functions - Internal Meeting

### ISSUE THREAD

**Issue by HoaDinh86** [OpenPecha/sherab.org#13]
1. Wish list courses
 Add a new button "Wishlist ♡" on course pages.

![Image](https://github.com/user-attachments/assets/2d3b8ad2-c66e-4e8a-9706-89f54a7a624a)

Create a new page call "My Wishlist" ([https://sherab.org/wishlist](https://sherab.org/wishlist)) to list all the courses that the user added. When clicking on the course name, It'll open the course page. Put the link after "Courses".

![Image](https://github.com/user-attachments/assets/52db2fd1-75f9-4fae-8514-dd3f334e40d3)

2. Order courses by "Course Number" on all the list pages:       
       - https://sherab.org/ > Course Categories
      - https://sherab.org/courses
      - https://sherab.org/dashboard
      - https://sherab.org/wishlist
      - inside each schools page: ie. [https://sherab.org/schools/palpung/](https://sherab.org/schools/palpung/)
      - inside each center page: ie: [https://sherab.org/schools/palpung/palpung-france/](https://sherab.org/schools/palpung/palpung-france/)

**Comment by parasc2021** [comment]
Yes, Point 3 will take more time.

**Comment by HoaDinh86** [comment]
hi Paras, then pls just do the first 2 points. I have removed the 3rd one.

**Comment by parasc2021** [comment]
Now we have wishlist function in live site https://sherab.org/
