### ISSUE TITLE
BU0001 -  Logos are distorted

### ISSUE THREAD

**Issue by HoaDinh86** [OpenPecha/sherab.org#14]
**Issue:**
Pages: 
1. [https://sherab.org/courses/](https://sherab.org/courses/)
2.  Course Categories: [https://sherab.org/](https://sherab.org/)
3. School pages: ie. [https://sherab.org/schools/sarah-college/](https://sherab.org/schools/sarah-college/)
4. Center page: ie. [https://sherab.org/schools/palpung/palpung-france/](https://sherab.org/schools/palpung/palpung-france/)

Some logos are distorted:

![Image](https://github.com/user-attachments/assets/11a3655f-14c4-4ab2-8f03-c1afd4258dd6)

**Suggest solution:** 
Set logos to the corresponding proportion of the origin photos.

**Comment by parasc2021** [comment]
Now logo updated.
