### ISSUE TITLE
CR0011: Add question content for Open Responses in Instructor Dashboard

### ISSUE THREAD

**Issue by HoaDinh86** [OpenPecha/sherab.org#15]
Issue: 
Currently, if in 1 unit, there are 2 open responses, the Open Responses in the Instructor Dashboard just shows the title of the unit, not the question content so it is difficult to know which question answers belong to. 
![Image](https://github.com/user-attachments/assets/faa12ceb-673e-4d81-ac94-e445a4f84073)
Link: [view-open_response_assessment](https://sherab.org/courses/course-v1:PalpungSangyelingFrance+FR2024-DBW2+01/instructor#view-open_response_assessment)

Suggestion solution:
Add question content after the title of the unit.  
It should be possible as current logic is able to break down 2 questions of the same unit into 2 different parts.

**Comment by parasc2021** [comment]
We can add one more column between "Unit Name" and "Assignment" where we can show question content.

This will take **6 hours**

**Comment by parasc2021** [comment]
The other option is you can use unique name in assessment.

![Instructor-Dashboard-Sherab-LMS-11-23-2024_05_03_PM](https://github.com/user-attachments/assets/824125a3-bfe0-4d27-9d14-cb5a2bcbd03c)

In studio you can modify this using below steps:
Go to studio and open same assessment
Click on "Edit"
![1-2-Introduction-au-Mahayana--11-23-2024_05_05_PM](https://github.com/user-attachments/assets/dc17a1ca-3c16-4b84-b19d-ee165edfb0b1)
Click on "Settings" and set "Display Name"
![1-2-Introduction-au-Mahayana--11-23-2024_05_07_PM](https://github.com/user-attachments/assets/d3bbc09d-afea-4168-8f7f-e1e3486b8918)

I hope this will help you.

Thanks

**Comment by HoaDinh86** [comment]
Yes, It works. Thank you!
